appname: 'sample_client'
layout: 'main'
charset: 'UTF-8'
template: 'simple'
session: 'simple'

oauth:
  auth_url: 'http://localhost:8080/oauth2/authorize'
  token_url: 'http://localhost:8080/oauth2/token'
  response_type: 'code'
  client_id: 'sample-client'
  client_secret: '75c35fbb-8294-4f33-9e34-b22672e262fc'
  redirect_uri: 'http://localhost:3000/susi_oauth'
  scopes:
    - 'read'

