appname: 'sample_client'
layout: 'main'
charset: 'UTF-8'
template: 'simple'
session: 'simple'

oauth:
  auth_url: 'http://localhost:8080/oauth2/authorize'
  token_url: 'http://localhost:8080/oauth2/token'
  response_type: 'code'
  client_id: 'sample-client'
  client_secret: '330bcb42-7447-4133-bcac-d55c5e1b506e'
  redirect_uri: 'http://localhost:3000/susi_oauth'
  scopes:
    - 'read'

