appname: 'sample_client'
layout: 'main'
charset: 'UTF-8'
template: 'simple'

oauth:
  url: 'http://localhost:8080/oauth2/authorize'
  response_type: 'code'
  client_id: 'sample-client'
  client_secret: 'secret'
  redirect_uri: 'http://localhost:3000/dashboard'

